AWSTemplateFormatVersion: "2010-09-09"
Description: "DynamoDB table used by DinkumCoin Api"

Parameters: 
  DinkumApiAppIamRole:
    Description: Name of IAM Role used by Application
    Type: String    

Outputs:
  WalletTableArn:
    Value: !GetAtt "DynamoDbWalletTable.Arn"

Resources:
  DynamoDbWalletTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Wallet
      AttributeDefinitions:
       - AttributeName: Id
         AttributeType: S
      KeySchema:
       - AttributeName: Id
         KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  
  DynamoDBIamPolicy:
    Type: AWS::IAM::Policy
    DependsOn: DynamoDbWalletTable
    Properties:
      PolicyName: dinkum-dynamodb
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
         - Effect: Allow
           Action:
             - dynamodb:GetItem
             - dynamodb:PutItem
             - dynamodb:DescribeTable
             - dynamodb:Scan
           Resource: arn:aws:dynamodb:*:*:table/Wallet
      Roles:
       - Ref: DinkumApiAppIamRole